---

resources:
- name: gitresource
  type: git
  check_every: 12h
  source:
    uri: https://github.com/julweber/dudebox
    branch: master
- name: concourse-kubernetes-poc-repo
  type: git
  check_every: 12h
  source:
    uri: https://github.com/julweber/concourse_kubernetes_poc
    branch: master
- name: every-10m
  type: time
  icon: clock-outline
  source:
    interval: 10m

jobs:
  - name: first-job
    public: true
    serial: true
    plan:
      - do:
        - get: every-10m
          trigger: true
        - in_parallel:
          - get: gitresource
            trigger: true
          - get: concourse-kubernetes-poc-repo
            trigger: true
      - task: ls-dir
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: julianweberdev/dudebox}
          run:
            path: sh
            args:
              - -exc
              - ls -la .
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: julianweberdev/dudebox}
          run:
            path: echo
            args: [hello world]

  - name: second-job
    public: true
    serial: true
    plan:
      - get: concourse-kubernetes-poc-repo
        passed:
          - first-job
      - task: dig-google-de
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: julianweberdev/dudebox}
          run:
            path: dig
            args: [www.google.de]
          
